[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "server"

[[bin]]
name = "client"

[dependencies]
prost = "0.13.5"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
