[package]
name = "backend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.89"
axum = { version = "0.7.5", features = ["macros"] }
listenfd = "1.0.1"
tokio = { version = "1.40.0", features = ["full"] }
